// <auto-generated />
using System;
using CustomerFeedback.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CustomerFeedback.Migrations
{
    [DbContext(typeof(CSATContext))]
    [Migration("20220210202549_UpdateDataTypes2")]
    partial class UpdateDataTypes2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CustomerFeedback.Models.Administrator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("VARCHAR(200)");

                    b.Property<string>("EmpId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR(50)");

                    b.Property<string>("NameFirst")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR(50)");

                    b.Property<string>("NameLast")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR(50)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("VARCHAR(20)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR(100)");

                    b.HasKey("Id");

                    b.ToTable("Administrator");
                });

            modelBuilder.Entity("CustomerFeedback.Models.CommodityType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR(100)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR(50)");

                    b.HasKey("Id");

                    b.ToTable("CommodityType");
                });

            modelBuilder.Entity("CustomerFeedback.Models.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("CustomerTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("VARCHAR(200)");

                    b.Property<string>("NameFirst")
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR(50)");

                    b.Property<string>("NameLast")
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR(50)");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("VARCHAR(1000)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("VARCHAR(20)");

                    b.Property<string>("Title")
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR(100)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Contact");
                });

            modelBuilder.Entity("CustomerFeedback.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("CommodityTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("ContactId")
                        .HasColumnType("int");

                    b.Property<int?>("CustomerTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("KpiTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR(100)");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("VARCHAR(1000)");

                    b.Property<string>("Url")
                        .HasMaxLength(200)
                        .HasColumnType("VARCHAR(200)");

                    b.HasKey("Id");

                    b.HasIndex("CommodityTypeId");

                    b.HasIndex("CustomerTypeId");

                    b.HasIndex("KpiTypeId");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("CustomerFeedback.Models.CustomerType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR(100)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("VARCHAR(10)");

                    b.HasKey("Id");

                    b.ToTable("CustomerType");
                });

            modelBuilder.Entity("CustomerFeedback.Models.KpiType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("VARCHAR(1000)");

                    b.Property<int?>("QuestionId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("VARCHAR(250)");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("KpiType");
                });

            modelBuilder.Entity("CustomerFeedback.Models.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CustomerTypeId")
                        .HasColumnType("int");

                    b.Property<int>("KpiTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Options")
                        .HasColumnType("VARCHAR");

                    b.Property<string>("QuestionType")
                        .HasColumnType("VARCHAR(100)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("VARCHAR(1000)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerTypeId");

                    b.ToTable("Question");
                });

            modelBuilder.Entity("CustomerFeedback.Models.Survey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("AdministratorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("VARCHAR(250)");

                    b.Property<DateTime?>("ExpireDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR(100)");

                    b.HasKey("Id");

                    b.HasIndex("AdministratorId");

                    b.HasIndex("CustomerTypeId");

                    b.ToTable("Survey");
                });

            modelBuilder.Entity("CustomerFeedback.Models.SurveyQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.Property<int?>("QuestionId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("QuestionId1")
                        .HasColumnType("int");

                    b.Property<int?>("SurveyId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("SurveyId1")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.HasIndex("QuestionId1");

                    b.HasIndex("SurveyId");

                    b.HasIndex("SurveyId1");

                    b.ToTable("SurveyQuestion");
                });

            modelBuilder.Entity("CustomerFeedback.Models.SurveyResponse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Answer")
                        .HasColumnType("VARCHAR(2000)");

                    b.Property<int?>("ContactId")
                        .HasColumnType("int");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int?>("QuestionId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("QuestionId1")
                        .HasColumnType("int");

                    b.Property<int?>("QuestionScore")
                        .HasColumnType("int");

                    b.Property<int?>("SurveyId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("SurveyId1")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SurveyResponseIteration")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ContactId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("QuestionId");

                    b.HasIndex("QuestionId1");

                    b.HasIndex("SurveyId");

                    b.HasIndex("SurveyId1");

                    b.ToTable("SurveyResponse");
                });

            modelBuilder.Entity("CustomerFeedback.Models.Contact", b =>
                {
                    b.HasOne("CustomerFeedback.Models.Customer", "Customer")
                        .WithMany("Contacts")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("CustomerFeedback.Models.Customer", b =>
                {
                    b.HasOne("CustomerFeedback.Models.CommodityType", "CommodityType")
                        .WithMany("Customers")
                        .HasForeignKey("CommodityTypeId");

                    b.HasOne("CustomerFeedback.Models.CustomerType", "CustomerType")
                        .WithMany("Customers")
                        .HasForeignKey("CustomerTypeId");

                    b.HasOne("CustomerFeedback.Models.KpiType", null)
                        .WithMany("Customers")
                        .HasForeignKey("KpiTypeId");

                    b.Navigation("CommodityType");

                    b.Navigation("CustomerType");
                });

            modelBuilder.Entity("CustomerFeedback.Models.KpiType", b =>
                {
                    b.HasOne("CustomerFeedback.Models.Question", null)
                        .WithMany("KpiType")
                        .HasForeignKey("QuestionId");
                });

            modelBuilder.Entity("CustomerFeedback.Models.Question", b =>
                {
                    b.HasOne("CustomerFeedback.Models.CustomerType", "CustomerType")
                        .WithMany("Questions")
                        .HasForeignKey("CustomerTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CustomerType");
                });

            modelBuilder.Entity("CustomerFeedback.Models.Survey", b =>
                {
                    b.HasOne("CustomerFeedback.Models.Administrator", "Administrator")
                        .WithMany("Surveys")
                        .HasForeignKey("AdministratorId");

                    b.HasOne("CustomerFeedback.Models.CustomerType", "CustomerType")
                        .WithMany("Surveys")
                        .HasForeignKey("CustomerTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Administrator");

                    b.Navigation("CustomerType");
                });

            modelBuilder.Entity("CustomerFeedback.Models.SurveyQuestion", b =>
                {
                    b.HasOne("CustomerFeedback.Models.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CustomerFeedback.Models.Question", null)
                        .WithMany("SurveyQuestions")
                        .HasForeignKey("QuestionId1");

                    b.HasOne("CustomerFeedback.Models.Survey", "Survey")
                        .WithMany()
                        .HasForeignKey("SurveyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CustomerFeedback.Models.Survey", null)
                        .WithMany("SurveyQuestions")
                        .HasForeignKey("SurveyId1");

                    b.Navigation("Question");

                    b.Navigation("Survey");
                });

            modelBuilder.Entity("CustomerFeedback.Models.SurveyResponse", b =>
                {
                    b.HasOne("CustomerFeedback.Models.Contact", "Contact")
                        .WithMany("SurveyResponses")
                        .HasForeignKey("ContactId");

                    b.HasOne("CustomerFeedback.Models.Customer", "Customer")
                        .WithMany("SurveyResponses")
                        .HasForeignKey("CustomerId");

                    b.HasOne("CustomerFeedback.Models.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CustomerFeedback.Models.Question", null)
                        .WithMany("SurveyResponses")
                        .HasForeignKey("QuestionId1");

                    b.HasOne("CustomerFeedback.Models.Survey", "Survey")
                        .WithMany()
                        .HasForeignKey("SurveyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CustomerFeedback.Models.Survey", null)
                        .WithMany("SurveyResponses")
                        .HasForeignKey("SurveyId1");

                    b.Navigation("Contact");

                    b.Navigation("Customer");

                    b.Navigation("Question");

                    b.Navigation("Survey");
                });

            modelBuilder.Entity("CustomerFeedback.Models.Administrator", b =>
                {
                    b.Navigation("Surveys");
                });

            modelBuilder.Entity("CustomerFeedback.Models.CommodityType", b =>
                {
                    b.Navigation("Customers");
                });

            modelBuilder.Entity("CustomerFeedback.Models.Contact", b =>
                {
                    b.Navigation("SurveyResponses");
                });

            modelBuilder.Entity("CustomerFeedback.Models.Customer", b =>
                {
                    b.Navigation("Contacts");

                    b.Navigation("SurveyResponses");
                });

            modelBuilder.Entity("CustomerFeedback.Models.CustomerType", b =>
                {
                    b.Navigation("Customers");

                    b.Navigation("Questions");

                    b.Navigation("Surveys");
                });

            modelBuilder.Entity("CustomerFeedback.Models.KpiType", b =>
                {
                    b.Navigation("Customers");
                });

            modelBuilder.Entity("CustomerFeedback.Models.Question", b =>
                {
                    b.Navigation("KpiType");

                    b.Navigation("SurveyQuestions");

                    b.Navigation("SurveyResponses");
                });

            modelBuilder.Entity("CustomerFeedback.Models.Survey", b =>
                {
                    b.Navigation("SurveyQuestions");

                    b.Navigation("SurveyResponses");
                });
#pragma warning restore 612, 618
        }
    }
}
